symmetricGroup = method()
symmetricGroup ZZ := List => n -> (
    if n < 1 then error("invalid matrix size");
    for sigma in permutations toList(1..n) list permutation sigma
    )

-- given a polytope P and a matrix M or list of matrices L
-- check that P is invariant under M or under each matrix in L
isSymmetric = method()
isSymmetric(Polyhedron, Matrix) := Boolean => (P, M) -> (
    V := sort vertices P; -- vertices of P are probably already sorted
    if numColumns M != numRows M then error("matrix must be square");
    if numColumns M != numRows V then error("matrix incompatible with polytope");
    MV := sort(M * V);
    R := ring MV;
    VR := V ** R; -- promote V in case V lies over a different ring
    MV == VR
    )

-- given a list of matrices,
-- check that a polyhedron is invariant under those matrices
isSymmetric(Polyhedron, List) := Boolean => (P, L) -> (
    all(L, M -> isSymmetric(P, M))
    )

-- group generated by a list of matrices
-- the user should guarantee that the group they generate is finite
-- in the case that the list is a singleton, we generate the elements as {g^0, g^1, ...}
generateGroup = method(
    Options => {
        Verbose => false,
        MaxComputeTime => 60, -- raises an exception if computation takes more than 60s
        }
    )
generateGroup List := List => opts -> L -> (
    local g;
    local h;
    local gh;
    local g';
    local groupElementsList;
    alarm(opts.MaxComputeTime);
    -- TODO : to print out the error nicely we can wrap this in a try-cach blockMatrixForm
    -- Check if we should do this or if there is a better standard practice
    if #L == 1 then (
        g = L_0 ;
        gIdentity := id_(target g) ;
        g' = g ;
        groupElementsList = {gIdentity};
        while not (g' == gIdentity) do (
            groupElementsList = append(groupElementsList, g') ;
            g' = g'*g ;
            )
        )
    else(
        -- construct a Cayley table of the group
        countMults := 0;
        groupElements := new MutableHashTable from for M in L list M => true;
        multsToCheck := new MutableList from flatten for i from 0 to #L-1 list for j from 0 to i list (L_i, L_j);
        while #multsToCheck > 0 do (
            -- pop one mult
            (g, h) = remove(multsToCheck, -1);
            gh = g * h;
            countMults = countMults +1;
            if not groupElements#?gh then (
                groupElements#gh = true;
                for f in keys groupElements do multsToCheck##multsToCheck = (gh, f);
                -- note that gh*gh is not necessary to add because we will get to it eventually by gh*g*h
                if opts.Verbose then (
                    print("found element: " | net gh | " (total elements: " | toString(#groupElements) | ")");
                    );
                );
            if opts.Verbose then (
                print("-- remains to check " | toString (#multsToCheck) | " multiplicaions");
                );
            );
        if opts.Verbose then (
            print("-- completed in " | toString countMults | " multiplications");
            );
        groupElementsList = keys groupElements ;
        ) ;
    alarm(0);
    groupElementsList  -- returns list of matrices
    )

-- takes a partition L of n and returns a permutation
-- with cycle type L
-- Unexported
partitionToPermutation = method()
partitionToPermutation List := List => L -> (
    cycleStart := 1;
    flatten for cycleLength in L list (
        cycleStart = cycleStart + cycleLength;
        for i from cycleStart - cycleLength to cycleStart -1 list (
            if i == cycleStart -1 then cycleStart - cycleLength else i + 1
            )
        )
    )

-- get conjugacy class reps for Sn
-- living as n x n permutation matrices
-- [Important] this method must produce partitions in the same order as
--   the function symmetricGroupTable in BettiCharacters
cycleTypeRepresentatives = method()
cycleTypeRepresentatives ZZ := List => n -> (
    S := toList \ partitions n;
    for s in S list matrix permutation partitionToPermutation s
    )

-- return the subset of points of P that are fixed by g
fixedPolytope = method()
fixedPolytope(Polyhedron, Matrix) := Polyhedron => (P, g) -> (
    n := numRows vertices P;
    if numRows g != numColumns g or numRows g != n then error("matrix size mismatch");
    gFixedSpace := coneFromHData(map(ZZ^0, ZZ^n, 0), g - id_(ZZ^n));
    intersection(P, gFixedSpace)
    )

-- representation ring of Sn over QQ
-- order of the rows and cols of character table
-- is given by 'partitions n'
representationRing = method(Options => {ReturnTable => false})
representationRing ZZ := opts -> n -> (
    a := getSymbol "a";
    x := getSymbol "X";
    R := QQ(monoid[a_1 .. a_n]);
    T := symmetricGroupTable R;
    M := sub(T.table, QQ);
    m := numColumns M;
    S := QQ(monoid[x_1 .. x_m]);
    if opts.ReturnTable then (S, M) else S
    )

-- EES of a polytope invariant under Sn
equivariantEhrhartSeries = method(
    Options => {
        ReturnTable => true,
        ReturnHStarList => true,
        ReturnClassReps => true
        })
equivariantEhrhartSeries Polyhedron := opts -> P -> (
    n := numRows vertices P;
    -- check P invariant under Sn
    g1 := matrix permutation rotate(1, toList(1..n));
    g2 := matrix extend(transposition 1, n);
    if not (isSymmetric(P, g1) and isSymmetric(P, g2)) then (
        error("polytope is not Sn invariant");
        );
    conjClassRepMats := cycleTypeRepresentatives n;
    fixedPolytopeList := (g -> fixedPolytope(P, g)) \ conjClassRepMats;
    (R, T) := representationRing(n, ReturnTable => true);
    m := numgens R; -- equals number of conj classes
    Rt := R[getSymbol "t"];
    t := Rt_0;
    hStarList := (Pg -> hStarPolynomial(Pg, Rt, ReturnDenominator => true)) \ fixedPolytopeList;
    ehrhartHStarList := for i from 0 to m-1 list (
        g := sub(conjClassRepMats_i, Rt);
        detRep := det(id_(Rt^n) - t*g);
        (hStarNum, hStarDenom) := hStarList_i;
        hStarDenom = value hStarDenom;
        if not zero((hStarNum * detRep) % hStarDenom) then (
            print "bad symmetry:";
            print g;
            error("equivariant hStar not polynomial");
            );
        (hStarNum * detRep) // hStarDenom
        ); -- list of Ehrhart H* polynomials note that denominator is det(I - tg)
    H := (matrix {ehrhartHStarList} * (inverse T) * transpose matrix {gens R})_(0,0);
    result := {H};
    if opts.ReturnTable then result = result | {T};
    if opts.ReturnClassReps then result = result | {toList \ partitions n};
    if opts.ReturnHStarList then result = result | {ehrhartHStarList};
    result
    )

-- equivariantEhrhartSeries(P, M) = evaluation of equivariantEhrhartSeries at M
equivariantEhrhartSeries(Polyhedron, Matrix) := opts -> (P, M) ->  (
    ehrhartSeries fixedPolytope(P, M)
    )

-- EES of a polytope under action of cyclic group generated by g
equivariantEhrhartSeries (Polyhedron, List) := opts -> (userP, userGList) -> (
    local P;
    local gList;
    n := ambDim userP;
    -- check that the polytope is codimension 1:
    (P, gList) = if dim userP < n-1 then  makeCodimensionOfSetupEqualOne(userP, userGList) else (userP, userGList);
    n = ambDim P;
    if dim P == n then (
        -- v -> (v,1) for each vertex v of P
        numVerts := numColumns vertices P;
        P = convexHull (vertices P || matrix {toList(numVerts : 1)});
        -- g -> g ++ {{1}} (direct sum)
        gList = apply(gList, g -> g ++ id_((ring g)^1));
        );
    -- check that P is symmetric with respect to gList
    for g in gList do (
        if not isSymmetric(P, g) then error("Polytope is not invariant under matrix");
        );
    if not #gList == 1 then (
        error("Expected one generator (only cyclic groups are supported now)");
        );
    groupElements := generateGroup gList;
    -- The order of the elements is {g^0, g^1, ..., g^s}
    fixedPolytopeList := apply(groupElements, g' -> fixedPolytope(P, g'));
    -- Character table has entries cyclotomic extension of QQ
    m := #groupElements;
    C := QQ(monoid[getSymbol "w"]);
    w := C_0;
    QQw := C / ideal cyclotomicPoly(m, w);
    w = QQw_0;
    -- representation ring
    X := getSymbol "X";
    R := QQw(monoid[X_1 .. X_m]);
    -- character table
    T := matrix for i from 0 to m-1 list for j from 0 to m-1 list w^(i*j);
    Rt := R[getSymbol "t"];
    t := Rt_0;
    hStarList := (Pg -> hStarPolynomial(Pg, Rt, ReturnDenominator => true)) \ fixedPolytopeList;
    ehrhartHStarList := for i from 0 to m-1 list (
        h := sub(groupElements_i, Rt);
        detRep := det(id_(Rt^n) - t*h);
        (hStarNum, hStarDenom) := hStarList_i;
        hStarDenom = value hStarDenom;
        if not zero((hStarNum * detRep) % hStarDenom) then (
            print "bad symmetry:";
            print h;
            error("equivariant hStar not polynomial");
            );
        (hStarNum * detRep) // hStarDenom
        ); -- list of Ehrhart H* polynomials note that denominator is det(I - tg)
    H := (matrix {ehrhartHStarList} * (inverse T) * transpose matrix {gens R})_(0,0);
    result := {H};
    if opts.ReturnTable then result = result | {T};
    if opts.ReturnClassReps then result = result | {groupElements};
    if opts.ReturnHStarList then result = result | {ehrhartHStarList};
    result
    )

-- if a polytope in RR^n has dimension d with d < n-1 then
-- for the purposes of computing the equivariant Ehrhart series
-- we need to restrict to some d+1 dimensional space
makeCodimensionOfSetupEqualOne = method()
makeCodimensionOfSetupEqualOne(Polyhedron, List) := (P, gList) -> (
    n := ambDim P;
    V := vertices P;
    F := reducedRowEchelonForm transpose V;
    inds := columnRankProfile mutableMatrix V;
    lower := id_(QQ^(n - #inds));
    F' := F^inds || ( matrix table(n-#inds, #inds, i -> 0) | lower);
    newGroupElements := apply(gList, g -> ((transpose F')^(-1)*g*(transpose F'))^{0 ..< #inds}_{0 ..< #inds});
    newVertices := ((transpose F')^(-1) * V)^inds;
    (convexHull newVertices, newGroupElements)
    )

-- obit polytope under Sn
-- expects a single column matrix: a point in QQ^n
orbitPolytope = method()
orbitPolytope Matrix := Polyhedron => p -> (
    n := numRows p;
    if numColumns p != 1 then error("expected matrix with 1 column");
    V := map(QQ^n, QQ^0, 0);
    for g in (symmetricGroup n) / matrix do (
        V = V | g*p;
        );
    convexHull V
    )

isEffective = method()
isEffective RingElement := Boolean => f -> (
    -- expected ring: (QQ[w]/(p(w)))[X_1..X_n][t]
    if not isInRepresentationRing f then error("invalid input");
    checkPositivity := g -> (
        -- g is either in QQ or ZZ, or a polynomial in some quotient ring
        k := ring g;
        if k === QQ or k === ZZ then g >= 0 else all(getCoefficients g, a -> a >= 0)
        );
    all(getCoefficients f, c -> all(getCoefficients c, i -> checkPositivity(i)))
)

-- isEffective helper method, gets coefficients and removes outer-most nesting of polynomial rings
getCoefficients = method()
getCoefficients RingElement := g -> apply(flatten entries last coefficients g, c -> sub(c, coefficientRing ring c));

-- isEffective error handling
isInRepresentationRing = method()
isInRepresentationRing RingElement := f -> (
    R1 := ring f;
    if not instance(R1, PolynomialRing) or #(gens R1) > 1 then (
        return false;
        );
    R2 := coefficientRing R1;
    if not instance(R2, PolynomialRing) then (
        return false;
        );
    -- check whether all coefficients of f are rational
    R3 := coefficientRing R2;
    -- expect: R3 to be a quotient ring with coefficient ring either QQ or ZZ
    if R3 === QQ or R3 === ZZ then (
        return true;
        );
    if instance(R3, QuotientRing) or instance(R3, PolynomialRing) then (
        -- check that coefficients in R3 do not involve any variables
        k := coefficientRing R3;
        if k =!= ZZ and k =!= QQ then (
            return false;
            );
        all(getCoefficients f, c -> all(getCoefficients c, g -> coefficientRing ring g === k))
        ) else (
        false
        )
    )


end ---

restart

P = convexHull transpose matrix "1,0,0,0;0,1,0,0;0,0,1,0"
g = matrix "0,1,0,0;1,0,0,0;0,0,1,0;0,0,0,1"

gList = {g}
H = equivariantEhrhartSeries(P, gList)
isEffective H

---

permutohedron := n -> convexHull transpose matrix permutations n

P = permutohedron 3;
L = equivariantEhrhartSeries P
H = first L
isEffective H


-- Todo: add some of these examples into the doc + tests

P = convexHull transpose matrix "1,0,0,0;0,1,0,0;0,0,1,0"
g = matrix "0,1,0,0;1,0,0,0;0,0,1,0;0,0,0,1"

gList = {g}

V = vertices P
tV = transpose V



P = convexHull transpose matrix "1,1,0,0;0,1,1,0;0,0,1,1;1,0,0,1"
g = matrix "0,0,0,1;1,0,0,0;0,1,0,0;0,0,1,0"

gList = {g}

V = vertices P
tV = transpose V
--reducedRowEchelonForm V
F = reducedRowEchelonForm tV

inds = rowRankProfile mutableMatrix tV

lower = id_(QQ^(n - #inds))

F^inds

F' = F^inds || ( matrix table(n-#inds, #inds, i -> 0) | lower)

transpose F'

FgF = (transpose F')^(-1)*
g*(transpose F')

newGroupElement = FgF^inds_inds

factor det(id_(QQ^#inds) - t*FgF^inds_inds)

V' = ((transpose F')^(-1) * V)^inds

newPolytope = convexHull V'


-- idea ::
fixedPolytopeList := apply(groupElements, g' -> fixedPolytope(P', g')); -- Todo get the fixed polytopes									Task (2)

hStarList := (Pg -> hStarPolynomial(Pg, Rt, ReturnDenominator => true)) \ fixedPolytopeList;


restart
uninstallPackage "EquivariantEhrhart"

restart
path = append(path, "./../")
installPackage "EquivariantEhrhart"

debug EquivariantEhrhart

P = convexHull transpose matrix "1,0,0,0;0,1,0,0;0,0,1,0"
g = matrix "0,1,0,0;1,0,0,0;0,0,1,0;0,0,0,1"

gList = {g}
equivariantEhrhartSeries(P, gList)

(userP, userGList) = (P, gList)

P = convexHull transpose matrix "1,1,0,0;0,1,1,0;0,0,1,1;1,0,0,1"
g = matrix "0,0,0,1;1,0,0,0;0,1,0,0;0,0,1,0"

equivariantEhrhartSeries(P, {g^2})



-- would need this (generateGroup) to compute conjugacy classes
